Add LinkCollection#structured_data
kzkn/gretel pull request #26
Opened 2020-10-30 21:25 UTC by dkniffin

Fixes #25

@kzkn I can definitely add tests to this, but I wanted to see what you think of it first.

2020-10-31 01:09 UTC, kzkn commented
@dkniffin 
LGTM. Keep going 😆
 
It would be great if you could include a sample of what you can write in the README.

2020-11-02 17:02 UTC, dkniffin commented
@kzkn I've updated the previous commit to include the test and the docs update. Let me know if you need anything else before merging this.

2020-11-03 06:28 UTC, kzkn requested changes
Almost, LGTM :+1: 
I'm commenting on some of the finer points. Please check.

2020-11-03 06:28 UTC, kzkn commented on lib/gretel/renderer.rb
> +            "position": i+1,
```suggestion
            "position": i + 1,
```

2020-11-03 06:28 UTC, kzkn commented on spec/lib/gretel/view_helpers_spec.rb
> +    end
Please add a spec for passing a URL that have no `/` suffix.

2020-11-03 16:00 UTC, dkniffin commented
@kzkn I've made those two updates you requested

2020-11-03 21:32 UTC, kzkn approved these changes

2020-11-03 21:33 UTC, kzkn commented
@dkniffin thanks!

2020-11-03 21:33 UTC, merged

2020-11-03 21:41 UTC, dkniffin commented
@kzkn Awesome, thank you! One more thing: can you bump the version so I can use the gem without pointing my Gemfile to github?

2020-11-04 08:35 UTC, kzkn commented
@dkniffin released as 4.2.0 :tada: